CREATE TABLE UserDetails(
USERID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CARDNO VARCHAR(15) NOT NULL UNIQUE,
PIN VARCHAR(6) NOT NULL UNIQUE,
ACCBAL NUMERIC(10,2) NOT NULL
)



CREATE TABLE TranDetails(
TRANID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
USERID INT FOREIGN KEY REFERENCES USERDETAILS(USERID),
TRANDATE DATE NOT NULL,
AMT INT NOT NULL,
TRANTYPE INT NOT NULL
)
